# Evan Cook, evan.cook@robotics.utias.utoronto.ca
# January 2024
# This file contains utilities for instantiating and manipulating pretrained PyTorch ImageNet-1K models.

import torchvision.models as models
import torch.nn as nn
import copy

# Helpers to get and set members of a pytorch model, using a list of strings and indices to specify the member.
# Arguments:
# - model, a pytorch model object
# - member_path, a list of strings and positive integers, describing the location of the member within the hierarchy of the model
# - value (for set_model_member), the value to set the member to
# Ex:
# ["block", 0, "fully_connected"] --> model.block[0].fully_connected
# ["classifier", 3] --> model.classifier[3]
# ["layers", 1, "linear", 0] --> model.layers[1].linear[0]
def get_model_member(model, member_path):
    ret = None
    for next_object in member_path:
        # String:
        if isinstance(next_object, str):
            if ret is None:
                ret = getattr(model, next_object)
            else:
                ret = getattr(ret, next_object)

        # Integer index:
        elif isinstance(next_object, int):
            if ret is not None:
                ret = ret[next_object]
            else:
                # Can't start with an integer index! For ex: backbone[0] isn't valid, backbone.layer[0] is valid.
                print("Invalid ordering of classifier backbone arguments")
                sys.exit(1)

        else:
            print("Error: invalid classifier backbone factory argument! {} must be an object name (string) or integer index".format(val))
            sys.exit(1)
    return ret


def set_model_member(model, member_path, value):
    parent = model
    for i, next_object in enumerate(member_path):
        is_last_entry = (i == len(member_path) - 1)

        # String:
        if isinstance(next_object, str):
            if is_last_entry:
                setattr(parent, next_object, value)
            else:
                parent = getattr(parent, next_object)
        # Integer index
        elif isinstance(next_object, int):
            if is_last_entry:
                parent[next_object] = value
            else:
                parent = parent[next_object]
        else:
            print("Error: invalid classifier backbone factory argument! {} must be an object name (string) or integer index".format(val))
            sys.exit(1)
    return



# Factory function that returns a pretrained backbone classifier model whose forward function returns a tuple of (logits, feature_vector).
# Arguments:
# - model constructor function
# - pretrained model weights (even if not using, necessary for the dataloader transforms)
# - the feature vector dimension
# - a list of string/index identifiers to locate the linear head in the pytorch pretrained model object (ex. ["lastblock", 3, "fullyconnected"])
# Example:
#   my_mobilenet = ClassifierFactory(models.mobilenet_v3_large, models.MobileNet_V3_Large_Weights.IMAGENET1K_V1, ["classifier", 3])
class ClassifierFactory(nn.Module):
    def __init__(self, model_constructor, model_weights, linear_head_path, pretrained=True):
        super(ClassifierFactory, self).__init__()

        self.transform = model_weights.transforms()
        weights = model_weights if pretrained else None
        self.backbone = model_constructor(weights=weights)

        # Goal: remove the linear head from the backbone, and re-add as our own linear layer at the end
        # so we can easily expose both feature vector and final logits (without using hooks)

        # First: get a reference to the old linear head object. For a general factory like this, we parse a list of names and indices.
        old_linear_head = get_model_member(self.backbone, linear_head_path)
        has_bias = old_linear_head.bias is not None

        # Second: copy the state / weights of the old linear head object to our new linear head object
        self.feature_dimension = old_linear_head.in_features
        self.linear = nn.Linear(self.feature_dimension, 1000, bias=has_bias)
        self.linear.load_state_dict(copy.deepcopy(old_linear_head.state_dict()))

        # Third: replace the old linear head with nn.Identity() so the backbone returns the feature vector
        set_model_member(self.backbone, linear_head_path, nn.Identity())

        # print("Modified classifier backbone:")
        # print(self.backbone)
        # print("Linear head:")
        # print(self.linear)

    def forward(self, x):
        feature = self.backbone(x)
        logits = self.linear(feature)
        return logits, feature

# This is all pretrained pytorch model + weight configs available.
# Retrieved from https://pytorch.org/vision/stable/models.html on 1/18/2024.
# Note: SqueezeNet1_0 and SqueezeNet1_1 are omitted, see comment below.

PRETRAINED_IMAGENET_MODELS = {
    'AlexNet': {
        'model': models.alexnet,
        'weights': models.AlexNet_Weights.IMAGENET1K_V1,
        'linear_head_path': ['classifier', 6],
        'feature_dim': 0,
        'top_1_acc': 56.522,
        'top_5_acc': 79.066,
        'params': 61.1,
        'gflops': 0.71,
        'feature_dimension': 4096,
    },
    'ConvNeXt_Base': {
        'model': models.convnext_base,
        'weights': models.ConvNeXt_Base_Weights.IMAGENET1K_V1,
        'linear_head_path': ['classifier', 2],
        'feature_dim': 0,
        'top_1_acc': 84.062,
        'top_5_acc': 96.87,
        'params': 88.6,
        'gflops': 15.36,
        'feature_dimension': 1024,
    },
    'ConvNeXt_Large': {
        'model': models.convnext_large,
        'weights': models.ConvNeXt_Large_Weights.IMAGENET1K_V1,
        'linear_head_path': ['classifier', 2],
        'feature_dim': 0,
        'top_1_acc': 84.414,
        'top_5_acc': 96.976,
        'params': 197.8,
        'gflops': 34.36,
        'feature_dimension': 1536,
    },
    'ConvNeXt_Small': {
        'model': models.convnext_small,
        'weights': models.ConvNeXt_Small_Weights.IMAGENET1K_V1,
        'linear_head_path': ['classifier', 2],
        'feature_dim': 0,
        'top_1_acc': 83.616,
        'top_5_acc': 96.65,
        'params': 50.2,
        'gflops': 8.68,
        'feature_dimension': 768,
    },
    'ConvNeXt_Tiny': {
        'model': models.convnext_tiny,
        'weights': models.ConvNeXt_Tiny_Weights.IMAGENET1K_V1,
        'linear_head_path': ['classifier', 2],
        'feature_dim': 0,
        'top_1_acc': 82.52,
        'top_5_acc': 96.146,
        'params': 28.6,
        'gflops': 4.46,
        'feature_dimension': 768,
    },
    'DenseNet121': {
        'model': models.densenet121,
        'weights': models.DenseNet121_Weights.IMAGENET1K_V1,
        'linear_head_path': ['classifier'],
        'feature_dim': 0,
        'top_1_acc': 74.434,
        'top_5_acc': 91.972,
        'params': 8.0,
        'gflops': 2.83,
        'feature_dimension': 1024,
    },
    'DenseNet161': {
        'model': models.densenet161,
        'weights': models.DenseNet161_Weights.IMAGENET1K_V1,
        'linear_head_path': ['classifier'],
        'feature_dim': 0,
        'top_1_acc': 77.138,
        'top_5_acc': 93.56,
        'params': 28.7,
        'gflops': 7.73,
        'feature_dimension': 2208,
    },
    'DenseNet169': {
        'model': models.densenet169,
        'weights': models.DenseNet169_Weights.IMAGENET1K_V1,
        'linear_head_path': ['classifier'],
        'feature_dim': 0,
        'top_1_acc': 75.6
,        'top_5_acc': 92.806,
        'params': 14.1,
        'gflops': 3.36,
        'feature_dimension': 1664,
    },
    'DenseNet201': {
        'model': models.densenet201,
        'weights': models.DenseNet201_Weights.IMAGENET1K_V1,
        'linear_head_path': ['classifier'],
        'feature_dim': 0,
        'top_1_acc': 76.896,
        'top_5_acc': 93.37,
        'params': 20.0,
        'gflops': 4.29,
        'feature_dimension': 1920,
    },
    'EfficientNet_B0': {
        'model': models.efficientnet_b0,
        'weights': models.EfficientNet_B0_Weights.IMAGENET1K_V1,
        'linear_head_path': ['classifier', 1],
        'feature_dim': 0,
        'top_1_acc': 77.692,
        'top_5_acc': 93.532,
        'params': 5.3,
        'gflops': 0.39,
        'feature_dimension': 1280,
    },
    'EfficientNet_B1_V1': {
        'model': models.efficientnet_b1,
        'weights': models.EfficientNet_B1_Weights.IMAGENET1K_V1,
        'linear_head_path': ['classifier', 1],
        'feature_dim': 0,
        'top_1_acc': 78.642,
        'top_5_acc': 94.186,
        'params': 7.8,
        'gflops': 0.69,
        'feature_dimension': 1280,
    },
    'EfficientNet_B1_V2': {
        'model': models.efficientnet_b1,
        'weights': models.EfficientNet_B1_Weights.IMAGENET1K_V2,
        'linear_head_path': ['classifier', 1],
        'feature_dim': 0,
        'top_1_acc': 79.838,
        'top_5_acc': 94.934,
        'params': 7.8,
        'gflops': 0.69,
        'feature_dimension': 1280,
    },
    'EfficientNet_B2': {
        'model': models.efficientnet_b2,
        'weights': models.EfficientNet_B2_Weights.IMAGENET1K_V1,
        'linear_head_path': ['classifier', 1],
        'feature_dim': 0,
        'top_1_acc': 80.608,
        'top_5_acc': 95.31,
        'params': 9.1,
        'gflops': 1.09,
        'feature_dimension': 1408,
    },
    'EfficientNet_B3': {
        'model': models.efficientnet_b3,
        'weights': models.EfficientNet_B3_Weights.IMAGENET1K_V1,
        'linear_head_path': ['classifier', 1],
        'feature_dim': 0,
        'top_1_acc': 82.008,
        'top_5_acc': 96.054,
        'params': 12.2,
        'gflops': 1.83,
        'feature_dimension': 1536,
    },
    'EfficientNet_B4': {
        'model': models.efficientnet_b4,
        'weights': models.EfficientNet_B4_Weights.IMAGENET1K_V1,
        'linear_head_path': ['classifier', 1],
        'feature_dim': 0,
        'top_1_acc': 83.384,
        'top_5_acc': 96.594,
        'params': 19.3,
        'gflops': 4.39,
        'feature_dimension': 1792,
    },
    'EfficientNet_B5': {
        'model': models.efficientnet_b5,
        'weights': models.EfficientNet_B5_Weights.IMAGENET1K_V1,
        'linear_head_path': ['classifier', 1],
        'feature_dim': 0,
        'top_1_acc': 83.444,
        'top_5_acc': 96.628,
        'params': 30.4,
        'gflops': 10.27,
        'feature_dimension': 2048,
    },
    'EfficientNet_B6': {
        'model': models.efficientnet_b6,
        'weights': models.EfficientNet_B6_Weights.IMAGENET1K_V1,
        'linear_head_path': ['classifier', 1],
        'feature_dim': 0,
        'top_1_acc': 84.008,
        'top_5_acc': 96.916,
        'params': 43.0,
        'gflops': 19.07,
        'feature_dimension': 2304,
    },
    'EfficientNet_B7': {
        'model': models.efficientnet_b7,
        'weights': models.EfficientNet_B7_Weights.IMAGENET1K_V1,
        'linear_head_path': ['classifier', 1],
        'feature_dim': 0,
        'top_1_acc': 84.122,
        'top_5_acc': 96.908,
        'params': 66.3,
        'gflops': 37.75,
        'feature_dimension': 2560,
    },
    'EfficientNet_V2_L': {
        'model': models.efficientnet_v2_l,
        'weights': models.EfficientNet_V2_L_Weights.IMAGENET1K_V1,
        'linear_head_path': ['classifier', 1],
        'feature_dim': 0,
        'top_1_acc': 85.808,
        'top_5_acc': 97.788,
        'params': 118.5,
        'gflops': 56.08,
        'feature_dimension': 1280,
    },
    'EfficientNet_V2_M': {
        'model': models.efficientnet_v2_m,
        'weights': models.EfficientNet_V2_M_Weights.IMAGENET1K_V1,
        'linear_head_path': ['classifier', 1],
        'feature_dim': 0,
        'top_1_acc': 85.112,
        'top_5_acc': 97.156,
        'params': 54.1,
        'gflops': 24.58,
        'feature_dimension': 1280,
    },
    'EfficientNet_V2_S': {
        'model': models.efficientnet_v2_s,
        'weights': models.EfficientNet_V2_S_Weights.IMAGENET1K_V1,
        'linear_head_path': ['classifier', 1],
        'feature_dim': 0,
        'top_1_acc': 84.228,
        'top_5_acc': 96.878,
        'params': 21.5,
        'gflops': 8.37,
        'feature_dimension': 1280,
    },
    'GoogLeNet': {
        'model': models.googlenet,
        'weights': models.GoogLeNet_Weights.IMAGENET1K_V1,
        'linear_head_path': ['fc'],
        'feature_dim': 0,
        'top_1_acc': 69.778,
        'top_5_acc': 89.53,
        'params': 6.6,
        'gflops': 1.5,
        'feature_dimension': 1024,
    },
    'Inception_V3': {
        'model': models.inception_v3,
        'weights': models.Inception_V3_Weights.IMAGENET1K_V1,
        'linear_head_path': ['fc'],
        'feature_dim': 0,
        'top_1_acc': 77.294,
        'top_5_acc': 93.45,
        'params': 27.2,
        'gflops': 5.71,
        'feature_dimension': 2048,
    },
    'MNASNet0_5': {
        'model': models.mnasnet0_5,
        'weights': models.MNASNet0_5_Weights.IMAGENET1K_V1,
        'linear_head_path': ['classifier', 1],
        'feature_dim': 0,
        'top_1_acc': 67.734,
        'top_5_acc': 87.49,
        'params': 2.2,
        'gflops': 0.1,
        'feature_dimension': 1280,
    },
    'MNASNet0_75': {
        'model': models.mnasnet0_75,
        'weights': models.MNASNet0_75_Weights.IMAGENET1K_V1,
        'linear_head_path': ['classifier', 1],
        'feature_dim': 0,
        'top_1_acc': 71.18,
        'top_5_acc': 90.496,
        'params': 3.2,
        'gflops': 0.21,
        'feature_dimension': 1280,
    },
    'MNASNet1_0': {
        'model': models.mnasnet1_0,
        'weights': models.MNASNet1_0_Weights.IMAGENET1K_V1,
        'linear_head_path': ['classifier', 1],
        'feature_dim': 0,
        'top_1_acc': 73.456,
        'top_5_acc': 91.51,
        'params': 4.4,
        'gflops': 0.31,
        'feature_dimension': 1280,
    },
    'MNASNet1_3': {
        'model': models.mnasnet1_3,
        'weights': models.MNASNet1_3_Weights.IMAGENET1K_V1,
        'linear_head_path': ['classifier', 1],
        'feature_dim': 0,
        'top_1_acc': 76.506,
        'top_5_acc': 93.522,
        'params': 6.3,
        'gflops': 0.53,
        'feature_dimension': 1280,
    },
    'MaxVit_T': {
        'model': models.maxvit_t,
        'weights': models.MaxVit_T_Weights.IMAGENET1K_V1,
        'linear_head_path': ['classifier', 5],
        'feature_dim': 0,
        'top_1_acc': 83.7,
        'top_5_acc': 96.722,
        'params': 30.9,
        'gflops': 5.56,
        'feature_dimension': 512,
    },
    'MobileNet_V2_V1': {
        'model': models.mobilenet_v2,
        'weights': models.MobileNet_V2_Weights.IMAGENET1K_V1,
        'linear_head_path': ['classifier', 1],
        'feature_dim': 0,
        'top_1_acc': 71.878,
        'top_5_acc': 90.286,
        'params': 3.5,
        'gflops': 0.3,
        'feature_dimension': 1280,
    },
    'MobileNet_V2_V2': {
        'model': models.mobilenet_v2,
        'weights': models.MobileNet_V2_Weights.IMAGENET1K_V2,
        'linear_head_path': ['classifier', 1],
        'feature_dim': 0,
        'top_1_acc': 72.154,
        'top_5_acc': 90.822,
        'params': 3.5,
        'gflops': 0.3,
        'feature_dimension': 1280,
    },
    'MobileNet_V3_Large_V1': {
        'model': models.mobilenet_v3_large,
        'weights': models.MobileNet_V3_Large_Weights.IMAGENET1K_V1,
        'linear_head_path': ['classifier', 3],
        'feature_dim': 0,
        'top_1_acc': 74.042,
        'top_5_acc': 91.34,
        'params': 5.5,
        'gflops': 0.22,
        'feature_dimension': 1280,
    },
    'MobileNet_V3_Large_V2': {
        'model': models.mobilenet_v3_large,
        'weights': models.MobileNet_V3_Large_Weights.IMAGENET1K_V2,
        'linear_head_path': ['classifier', 3],
        'feature_dim': 0,
        'top_1_acc': 75.274,
        'top_5_acc': 92.566,
        'params': 5.5,
        'gflops': 0.22,
        'feature_dimension': 1280,
    },
    'MobileNet_V3_Small': {
        'model': models.mobilenet_v3_small,
        'weights': models.MobileNet_V3_Small_Weights.IMAGENET1K_V1,
        'linear_head_path': ['classifier', 3],
        'feature_dim': 0,
        'top_1_acc': 67.668,
        'top_5_acc': 87.402,
        'params': 2.5,
        'gflops': 0.06,
        'feature_dimension': 1024,
    },
    'RegNet_X_16GF_V1': {
        'model': models.regnet_x_16gf,
        'weights': models.RegNet_X_16GF_Weights.IMAGENET1K_V1,
        'linear_head_path': ['fc'],
        'feature_dim': 0,
        'top_1_acc': 80.058,
        'top_5_acc': 94.944,
        'params': 54.3,
        'gflops': 15.94,
        'feature_dimension': 2048,
    },
    'RegNet_X_16GF_V2': {
        'model': models.regnet_x_16gf,
        'weights': models.RegNet_X_16GF_Weights.IMAGENET1K_V2,
        'linear_head_path': ['fc'],
        'feature_dim': 0,
        'top_1_acc': 82.716,
        'top_5_acc': 96.196,
        'params': 54.3,
        'gflops': 15.94,
        'feature_dimension': 2048,
    },
    'RegNet_X_1_6GF_V1': {
        'model': models.regnet_x_1_6gf,
        'weights': models.RegNet_X_1_6GF_Weights.IMAGENET1K_V1,
        'linear_head_path': ['fc'],
        'feature_dim': 0,
        'top_1_acc': 77.04,
        'top_5_acc': 93.44,
        'params': 9.2,
        'gflops': 1.6,
        'feature_dimension': 912,
    },
    'RegNet_X_1_6GF_V2': {
        'model': models.regnet_x_1_6gf,
        'weights': models.RegNet_X_1_6GF_Weights.IMAGENET1K_V2,
        'linear_head_path': ['fc'],
        'feature_dim': 0,
        'top_1_acc': 79.668,
        'top_5_acc': 94.922,
        'params': 9.2,
        'gflops': 1.6,
        'feature_dimension': 912,
    },
    'RegNet_X_32GF_V1': {
        'model': models.regnet_x_32gf,
        'weights': models.RegNet_X_32GF_Weights.IMAGENET1K_V1,
        'linear_head_path': ['fc'],
        'feature_dim': 0,
        'top_1_acc': 80.622,
        'top_5_acc': 95.248,
        'params': 107.8,
        'gflops': 31.74,
        'feature_dimension': 2520,
    },
    'RegNet_X_32GF_V2': {
        'model': models.regnet_x_32gf,
        'weights': models.RegNet_X_32GF_Weights.IMAGENET1K_V2,
        'linear_head_path': ['fc'],
        'feature_dim': 0,
        'top_1_acc': 83.014,
        'top_5_acc': 96.288,
        'params': 107.8,
        'gflops': 31.74,
        'feature_dimension': 2520,
    },
    'RegNet_X_3_2GF_V1': {
        'model': models.regnet_x_3_2gf,
        'weights': models.RegNet_X_3_2GF_Weights.IMAGENET1K_V1,
        'linear_head_path': ['fc'],
        'feature_dim': 0,
        'top_1_acc': 78.364,
        'top_5_acc': 93.992,
        'params': 15.3,
        'gflops': 3.18,
        'feature_dimension': 1008,
    },
    'RegNet_X_3_2GF_V2': {
        'model': models.regnet_x_3_2gf,
        'weights': models.RegNet_X_3_2GF_Weights.IMAGENET1K_V2,
        'linear_head_path': ['fc'],
        'feature_dim': 0,
        'top_1_acc': 81.196,
        'top_5_acc': 95.43,
        'params': 15.3,
        'gflops': 3.18,
        'feature_dimension': 1008,
    },
    'RegNet_X_400MF_V1': {
        'model': models.regnet_x_400mf,
        'weights': models.RegNet_X_400MF_Weights.IMAGENET1K_V1,
        'linear_head_path': ['fc'],
        'feature_dim': 0,
        'top_1_acc': 72.834,
        'top_5_acc': 90.95,
        'params': 5.5,
        'gflops': 0.41,
        'feature_dimension': 400,
    },
    'RegNet_X_400MF_V2': {
        'model': models.regnet_x_400mf,
        'weights': models.RegNet_X_400MF_Weights.IMAGENET1K_V2,
        'linear_head_path': ['fc'],
        'feature_dim': 0,
        'top_1_acc': 74.864,
        'top_5_acc': 92.322,
        'params': 5.5,
        'gflops': 0.41,
        'feature_dimension': 400,
    },
    'RegNet_X_800MF_V1': {
        'model': models.regnet_x_800mf,
        'weights': models.RegNet_X_800MF_Weights.IMAGENET1K_V1,
        'linear_head_path': ['fc'],
        'feature_dim': 0,
        'top_1_acc': 75.212,
        'top_5_acc': 92.348,
        'params': 7.3,
        'gflops': 0.8,
        'feature_dimension': 672,
    },
    'RegNet_X_800MF_V2': {
        'model': models.regnet_x_800mf,
        'weights': models.RegNet_X_800MF_Weights.IMAGENET1K_V2,
        'linear_head_path': ['fc'],
        'feature_dim': 0,
        'top_1_acc': 77.522,
        'top_5_acc': 93.826,
        'params': 7.3,
        'gflops': 0.8,
        'feature_dimension': 672,
    },
    'RegNet_X_8GF_V1': {
        'model': models.regnet_x_8gf,
        'weights': models.RegNet_X_8GF_Weights.IMAGENET1K_V1,
        'linear_head_path': ['fc'],
        'feature_dim': 0,
        'top_1_acc': 79.344,
        'top_5_acc': 94.686,
        'params': 39.6,
        'gflops': 8.0,
        'feature_dimension': 1920,
    },
    'RegNet_X_8GF_V2': {
        'model': models.regnet_x_8gf,
        'weights': models.RegNet_X_8GF_Weights.IMAGENET1K_V2,
        'linear_head_path': ['fc'],
        'feature_dim': 0,
        'top_1_acc': 81.682,
        'top_5_acc': 95.678,
        'params': 39.6,
        'gflops': 8.0,
        'feature_dimension': 1920,
    },
    'RegNet_Y_128GF_V1': {
        'model': models.regnet_y_128gf,
        'weights': models.RegNet_Y_128GF_Weights.IMAGENET1K_SWAG_E2E_V1,
        'linear_head_path': ['fc'],
        'feature_dim': 0,
        'top_1_acc': 88.228,
        'top_5_acc': 98.682,
        'params': 644.8,
        'gflops': 374.57,
        'feature_dimension': 7392,
    },
    'RegNet_Y_128GF_V2': {
        'model': models.regnet_y_128gf,
        'weights': models.RegNet_Y_128GF_Weights.IMAGENET1K_SWAG_LINEAR_V1,
        'linear_head_path': ['fc'],
        'feature_dim': 0,
        'top_1_acc': 86.068,
        'top_5_acc': 97.844,
        'params': 644.8,
        'gflops': 127.52,
        'feature_dimension': 7392,
    },
    'RegNet_Y_16GF_V1': {
        'model': models.regnet_y_16gf,
        'weights': models.RegNet_Y_16GF_Weights.IMAGENET1K_V1,
        'linear_head_path': ['fc'],
        'feature_dim': 0,
        'top_1_acc': 80.424,
        'top_5_acc': 95.24,
        'params': 83.6,
        'gflops': 15.91,
        'feature_dimension': 3024,
    },
    'RegNet_Y_16GF_V2': {
        'model': models.regnet_y_16gf,
        'weights': models.RegNet_Y_16GF_Weights.IMAGENET1K_V2,
        'linear_head_path': ['fc'],
        'feature_dim': 0,
        'top_1_acc': 82.886,
        'top_5_acc': 96.328,
        'params': 83.6,
        'gflops': 15.91,
        'feature_dimension': 3024,
    },
    'RegNet_Y_16GF_SWAG_E2E_V1': {
        'model': models.regnet_y_16gf,
        'weights': models.RegNet_Y_16GF_Weights.IMAGENET1K_SWAG_E2E_V1,
        'linear_head_path': ['fc'],
        'feature_dim': 0,
        'top_1_acc': 86.012,
        'top_5_acc': 98.054,
        'params': 83.6,
        'gflops': 46.73,
        'feature_dimension': 3024,
    },
    'RegNet_Y_16GF_SWAG_LINEAR_V1': {
        'model': models.regnet_y_16gf,
        'weights': models.RegNet_Y_16GF_Weights.IMAGENET1K_SWAG_LINEAR_V1,
        'linear_head_path': ['fc'],
        'feature_dim': 0,
        'top_1_acc': 83.976,
        'top_5_acc': 97.244,
        'params': 83.6,
        'gflops': 15.91,
        'feature_dimension': 3024,
    },
    'RegNet_Y_1_6GF_V1': {
        'model': models.regnet_y_1_6gf,
        'weights': models.RegNet_Y_1_6GF_Weights.IMAGENET1K_V1,
        'linear_head_path': ['fc'],
        'feature_dim': 0,
        'top_1_acc': 77.95,
        'top_5_acc': 93.966,
        'params': 11.2,
        'gflops': 1.61,
        'feature_dimension': 888,
    },
    'RegNet_Y_1_6GF_V2': {
        'model': models.regnet_y_1_6gf,
        'weights': models.RegNet_Y_1_6GF_Weights.IMAGENET1K_V2,
        'linear_head_path': ['fc'],
        'feature_dim': 0,
        'top_1_acc': 80.876,
        'top_5_acc': 95.444,
        'params': 11.2,
        'gflops': 1.61,
        'feature_dimension': 888,
    },
    'RegNet_Y_32GF_V1': {
        'model': models.regnet_y_32gf,
        'weights': models.RegNet_Y_32GF_Weights.IMAGENET1K_V1,
        'linear_head_path': ['fc'],
        'feature_dim': 0,
        'top_1_acc': 80.878,
        'top_5_acc': 95.34,
        'params': 145.0,
        'gflops': 32.28,
        'feature_dimension': 3712,
    },
    'RegNet_Y_32GF_V2': {
        'model': models.regnet_y_32gf,
        'weights': models.RegNet_Y_32GF_Weights.IMAGENET1K_V2,
        'linear_head_path': ['fc'],
        'feature_dim': 0,
        'top_1_acc': 83.368,
        'top_5_acc': 96.498,
        'params': 145.0,
        'gflops': 32.28,
        'feature_dimension': 3712,
    },
    'RegNet_Y_32GF_SWAG_E2E_V1': {
        'model': models.regnet_y_32gf,
        'weights': models.RegNet_Y_32GF_Weights.IMAGENET1K_SWAG_E2E_V1,
        'linear_head_path': ['fc'],
        'feature_dim': 0,
        'top_1_acc': 86.838,
        'top_5_acc': 98.362,
        'params': 145.0,
        'gflops': 94.83,
        'feature_dimension': 3712,
    },
    'RegNet_Y_32GF_SWAG_LINEAR_V1': {
        'model': models.regnet_y_32gf,
        'weights': models.RegNet_Y_32GF_Weights.IMAGENET1K_SWAG_LINEAR_V1,
        'linear_head_path': ['fc'],
        'feature_dim': 0,
        'top_1_acc': 84.622,
        'top_5_acc': 97.48,
        'params': 145.0,
        'gflops': 32.28,
        'feature_dimension': 3712,
    },
    'RegNet_Y_3_2GF_V1': {
        'model': models.regnet_y_3_2gf,
        'weights': models.RegNet_Y_3_2GF_Weights.IMAGENET1K_V1,
        'linear_head_path': ['fc'],
        'feature_dim': 0,
        'top_1_acc': 78.948,
        'top_5_acc': 94.576,
        'params': 19.4,
        'gflops': 3.18,
        'feature_dimension': 1512,
    },
    'RegNet_Y_3_2GF_V2': {
        'model': models.regnet_y_3_2gf,
        'weights': models.RegNet_Y_3_2GF_Weights.IMAGENET1K_V2,
        'linear_head_path': ['fc'],
        'feature_dim': 0,
        'top_1_acc': 81.982,
        'top_5_acc': 95.972,
        'params': 19.4,
        'gflops': 3.18,
        'feature_dimension': 1512,
    },
    'RegNet_Y_400MF_V1': {
        'model': models.regnet_y_400mf,
        'weights': models.RegNet_Y_400MF_Weights.IMAGENET1K_V1,
        'linear_head_path': ['fc'],
        'feature_dim': 0,
        'top_1_acc': 74.046,
        'top_5_acc': 91.716,
        'params': 4.3,
        'gflops': 0.4,
        'feature_dimension': 440,
    },
    'RegNet_Y_400MF_V2': {
        'model': models.regnet_y_400mf,
        'weights': models.RegNet_Y_400MF_Weights.IMAGENET1K_V2,
        'linear_head_path': ['fc'],
        'feature_dim': 0,
        'top_1_acc': 75.804,
        'top_5_acc': 92.742,
        'params': 4.3,
        'gflops': 0.4,
        'feature_dimension': 440,
    },
    'RegNet_Y_800MF_V1': {
        'model': models.regnet_y_800mf,
        'weights': models.RegNet_Y_800MF_Weights.IMAGENET1K_V1,
        'linear_head_path': ['fc'],
        'feature_dim': 0,
        'top_1_acc': 76.42,
        'top_5_acc': 93.136,
        'params': 6.4,
        'gflops': 0.83,
        'feature_dimension': 784,
    },
    'RegNet_Y_800MF_V2': {
        'model': models.regnet_y_800mf,
        'weights': models.RegNet_Y_800MF_Weights.IMAGENET1K_V2,
        'linear_head_path': ['fc'],
        'feature_dim': 0,
        'top_1_acc': 78.828,
        'top_5_acc': 94.502,
        'params': 6.4,
        'gflops': 0.83,
        'feature_dimension': 784,
    },
    'RegNet_Y_8GF_V1': {
        'model': models.regnet_y_8gf,
        'weights': models.RegNet_Y_8GF_Weights.IMAGENET1K_V1,
        'linear_head_path': ['fc'],
        'feature_dim': 0,
        'top_1_acc': 80.032,
        'top_5_acc': 95.048,
        'params': 39.4,
        'gflops': 8.47,
        'feature_dimension': 2016,
    },
    'RegNet_Y_8GF_V2': {
        'model': models.regnet_y_8gf,
        'weights': models.RegNet_Y_8GF_Weights.IMAGENET1K_V2,
        'linear_head_path': ['fc'],
        'feature_dim': 0,
        'top_1_acc': 82.828,
        'top_5_acc': 96.33,
        'params': 39.4,
        'gflops': 8.47,
        'feature_dimension': 2016,
    },
    'ResNeXt101_32X8D_V1': {
        'model': models.resnext101_32x8d,
        'weights': models.ResNeXt101_32X8D_Weights.IMAGENET1K_V1,
        'linear_head_path': ['fc'],
        'feature_dim': 0,
        'top_1_acc': 79.312,
        'top_5_acc': 94.526,
        'params': 88.8,
        'gflops': 16.41,
        'feature_dimension': 2048,
    },
    'ResNeXt101_32X8D_V2': {
        'model': models.resnext101_32x8d,
        'weights': models.ResNeXt101_32X8D_Weights.IMAGENET1K_V2,
        'linear_head_path': ['fc'],
        'feature_dim': 0,
        'top_1_acc': 82.834,
        'top_5_acc': 96.228,
        'params': 88.8,
        'gflops': 16.41,
        'feature_dimension': 2048,
    },
    'ResNeXt101_64X4D': {
        'model': models.resnext101_64x4d,
        'weights': models.ResNeXt101_64X4D_Weights.IMAGENET1K_V1,
        'linear_head_path': ['fc'],
        'feature_dim': 0,
        'top_1_acc': 83.246,
        'top_5_acc': 96.454,
        'params': 83.5,
        'gflops': 15.46,
        'feature_dimension': 2048,
    },
    'ResNeXt50_32X4D_V1': {
        'model': models.resnext50_32x4d,
        'weights': models.ResNeXt50_32X4D_Weights.IMAGENET1K_V1,
        'linear_head_path': ['fc'],
        'feature_dim': 0,
        'top_1_acc': 77.618,
        'top_5_acc': 93.698,
        'params': 25.0,
        'gflops': 4.23,
        'feature_dimension': 2048,
    },
    'ResNeXt50_32X4D_V2': {
        'model': models.resnext50_32x4d,
        'weights': models.ResNeXt50_32X4D_Weights.IMAGENET1K_V2,
        'linear_head_path': ['fc'],
        'feature_dim': 0,
        'top_1_acc': 81.198,
        'top_5_acc': 95.34,
        'params': 25.0,
        'gflops': 4.23,
        'feature_dimension': 2048,
    },
    'ResNet101_V1': {
        'model': models.resnet101,
        'weights': models.ResNet101_Weights.IMAGENET1K_V1,
        'linear_head_path': ['fc'],
        'feature_dim': 0,
        'top_1_acc': 77.374,
        'top_5_acc': 93.546,
        'params': 44.5,
        'gflops': 7.8,
        'feature_dimension': 2048,
    },
    'ResNet101_V2': {
        'model': models.resnet101,
        'weights': models.ResNet101_Weights.IMAGENET1K_V2,
        'linear_head_path': ['fc'],
        'feature_dim': 0,
        'top_1_acc': 81.886,
        'top_5_acc': 95.78,
        'params': 44.5,
        'gflops': 7.8,
        'feature_dimension': 2048,
    },
    'ResNet152_V1': {
        'model': models.resnet152,
        'weights': models.ResNet152_Weights.IMAGENET1K_V1,
        'linear_head_path': ['fc'],
        'feature_dim': 0,
        'top_1_acc': 78.312,
        'top_5_acc': 94.046,
        'params': 60.2,
        'gflops': 11.51,
        'feature_dimension': 2048,
    },
    'ResNet152_V2': {
        'model': models.resnet152,
        'weights': models.ResNet152_Weights.IMAGENET1K_V2,
        'linear_head_path': ['fc'],
        'feature_dim': 0,
        'top_1_acc': 82.284,
        'top_5_acc': 96.002,
        'params': 60.2,
        'gflops': 11.51,
        'feature_dimension': 2048,
    },
    'ResNet18': {
        'model': models.resnet18,
        'weights': models.ResNet18_Weights.IMAGENET1K_V1,
        'linear_head_path': ['fc'],
        'feature_dim': 0,
        'top_1_acc': 69.758,
        'top_5_acc': 89.078,
        'params': 11.7,
        'gflops': 1.81,
        'feature_dimension': 512,
    },
    'ResNet34': {
        'model': models.resnet34,
        'weights': models.ResNet34_Weights.IMAGENET1K_V1,
        'linear_head_path': ['fc'],
        'feature_dim': 0,
        'top_1_acc': 73.314,
        'top_5_acc': 91.42,
        'params': 21.8,
        'gflops': 3.66,
        'feature_dimension': 512,
    },
    'ResNet50_V1': {
        'model': models.resnet50,
        'weights': models.ResNet50_Weights.IMAGENET1K_V1,
        'linear_head_path': ['fc'],
        'feature_dim': 0,
        'top_1_acc': 76.13,
        'top_5_acc': 92.862,
        'params': 25.6,
        'gflops': 4.09,
        'feature_dimension': 2048,
    },
    'ResNet50_V2': {
        'model': models.resnet50,
        'weights': models.ResNet50_Weights.IMAGENET1K_V2,
        'linear_head_path': ['fc'],
        'feature_dim': 0,
        'top_1_acc': 80.858,
        'top_5_acc': 95.434,
        'params': 25.6,
        'gflops': 4.09,
        'feature_dimension': 2048,
    },
    'ShuffleNet_V2_X0_5': {
        'model': models.shufflenet_v2_x0_5,
        'weights': models.ShuffleNet_V2_X0_5_Weights.IMAGENET1K_V1,
        'linear_head_path': ['fc'],
        'feature_dim': 0,
        'top_1_acc': 60.552,
        'top_5_acc': 81.746,
        'params': 1.4,
        'gflops': 0.04,
        'feature_dimension': 1024,
    },
    'ShuffleNet_V2_X1_0': {
        'model': models.shufflenet_v2_x1_0,
        'weights': models.ShuffleNet_V2_X1_0_Weights.IMAGENET1K_V1,
        'linear_head_path': ['fc'],
        'feature_dim': 0,
        'top_1_acc': 69.362,
        'top_5_acc': 88.316,
        'params': 2.3,
        'gflops': 0.14,
        'feature_dimension': 1024,
    },
    'ShuffleNet_V2_X1_5': {
        'model': models.shufflenet_v2_x1_5,
        'weights': models.ShuffleNet_V2_X1_5_Weights.IMAGENET1K_V1,
        'linear_head_path': ['fc'],
        'feature_dim': 0,
        'top_1_acc': 72.996,
        'top_5_acc': 91.086,
        'params': 3.5,
        'gflops': 0.3,
        'feature_dimension': 1024,
    },
    'ShuffleNet_V2_X2_0': {
        'model': models.shufflenet_v2_x2_0,
        'weights': models.ShuffleNet_V2_X2_0_Weights.IMAGENET1K_V1,
        'linear_head_path': ['fc'],
        'feature_dim': 0,
        'top_1_acc': 76.23,
        'top_5_acc': 93.006,
        'params': 7.4,
        'gflops': 0.58,
        'feature_dimension': 2048,
    },
    # ERROR: final layer of SqueezeNet is AdaptiveAvgPool2d(output_size=(1, 1)), and not a linear 
    # layer
    # 'SqueezeNet1_0': {
    #     'model': models.squeezenet1_0,
    #     'weights': models.SqueezeNet1_0_Weights.IMAGENET1K_V1,
    #     'linear_head_path': ['classifier', 3],
    #     'feature_dim':  0,
    #     'top_1_acc': 58.092,
    #     'top_5_acc': 80.42,
    #     'params': 1.2,
    #     'gflops': 0.82,
    #     'feature_dimension': None,
    # },
    # 'SqueezeNet1_1': {
    #     'model': models.squeezenet1_1,
    #     'weights': models.SqueezeNet1_1_Weights.IMAGENET1K_V1,
    #     'linear_head_path': ['classifier', 3],
    #     'feature_dim':  0,
    #     'top_1_acc': 58.178,
    #     'top_5_acc': 80.624,
    #     'params': 1.2,
    #     'gflops': 0.35,
    #     'feature_dimension': None,
    # },
    'Swin_B': {
        'model': models.swin_b,
        'weights': models.Swin_B_Weights.IMAGENET1K_V1,
        'linear_head_path': ['head'],
        'feature_dim': 0,
        'top_1_acc': 83.582,
        'top_5_acc': 96.64,
        'params': 87.8,
        'gflops': 15.43,
        'feature_dimension': 1024,
    },
    'Swin_S': {
        'model': models.swin_s,
        'weights': models.Swin_S_Weights.IMAGENET1K_V1,
        'linear_head_path': ['head'],
        'feature_dim': 0,
        'top_1_acc': 83.196,
        'top_5_acc': 96.36,
        'params': 49.6,
        'gflops': 8.74,
        'feature_dimension': 768,
    },
    'Swin_T': {
        'model': models.swin_t,
        'weights': models.Swin_T_Weights.IMAGENET1K_V1,
        'linear_head_path': ['head'],
        'feature_dim': 0,
        'top_1_acc': 81.474,
        'top_5_acc': 95.776,
        'params': 28.3,
        'gflops': 4.49,
        'feature_dimension': 768,
    },
    'Swin_V2_B': {
        'model': models.swin_v2_b,
        'weights': models.Swin_V2_B_Weights.IMAGENET1K_V1,
        'linear_head_path': ['head'],
        'feature_dim': 0,
        'top_1_acc': 84.112,
        'top_5_acc': 96.864,
        'params': 87.9,
        'gflops': 20.32,
        'feature_dimension': 1024,
    },
    'Swin_V2_S': {
        'model': models.swin_v2_s,
        'weights': models.Swin_V2_S_Weights.IMAGENET1K_V1,
        'linear_head_path': ['head'],
        'feature_dim': 0,
        'top_1_acc': 83.712,
        'top_5_acc': 96.816,
        'params': 49.7,
        'gflops': 11.55,
        'feature_dimension': 768,
    },
    'Swin_V2_T': {
        'model': models.swin_v2_t,
        'weights': models.Swin_V2_T_Weights.IMAGENET1K_V1,
        'linear_head_path': ['head'],
        'feature_dim': 0,
        'top_1_acc': 82.072,
        'top_5_acc': 96.132,
        'params': 28.4,
        'gflops': 5.94,
        'feature_dimension': 768,
    },
    'VGG11_BN': {
        'model': models.vgg11_bn,
        'weights': models.VGG11_BN_Weights.IMAGENET1K_V1,
        'linear_head_path': ['classifier', 6],
        'feature_dim': 0,
        'top_1_acc': 70.37,
        'top_5_acc': 89.81,
        'params': 132.9,
        'gflops': 7.61,
        'feature_dimension': 4096,
    },
    'VGG11': {
        'model': models.vgg11,
        'weights': models.VGG11_Weights.IMAGENET1K_V1,
        'linear_head_path': ['classifier', 6],
        'feature_dim': 0,
        'top_1_acc': 69.02,
        'top_5_acc': 88.628,
        'params': 132.9,
        'gflops': 7.61,
        'feature_dimension': 4096,
    },
    'VGG13_BN': {
        'model': models.vgg13_bn,
        'weights': models.VGG13_BN_Weights.IMAGENET1K_V1,
        'linear_head_path': ['classifier', 6],
        'feature_dim': 0,
        'top_1_acc': 71.586,
        'top_5_acc': 90.374,
        'params': 133.1,
        'gflops': 11.31,
        'feature_dimension': 4096,
    },
    'VGG13': {
        'model': models.vgg13,
        'weights': models.VGG13_Weights.IMAGENET1K_V1,
        'linear_head_path': ['classifier', 6],
        'feature_dim': 0,
        'top_1_acc': 69.928,
        'top_5_acc': 89.246,
        'params': 133.0,
        'gflops': 11.31,
        'feature_dimension': 4096,
    },
    'VGG16_BN': {
        'model': models.vgg16_bn,
        'weights': models.VGG16_BN_Weights.IMAGENET1K_V1,
        'linear_head_path': ['classifier', 6],
        'feature_dim': 0,
        'top_1_acc': 73.36,
        'top_5_acc': 91.516,
        'params': 138.4,
        'gflops': 15.47,
        'feature_dimension': 4096,
    },
    'VGG16_V1': {
        'model': models.vgg16,
        'weights': models.VGG16_Weights.IMAGENET1K_V1,
        'linear_head_path': ['classifier', 6],
        'feature_dim': 0,
        'top_1_acc': 71.592,
        'top_5_acc': 90.382,
        'params': 138.4,
        'gflops': 15.47,
        'feature_dimension': 4096,
    },
    'VGG16_FEATURES': {
        'model': models.vgg16,
        'weights': models.VGG16_Weights.IMAGENET1K_FEATURES,
        'linear_head_path': ['classifier', 6],
        'feature_dim': 0,
        'top_1_acc': 0.0, # Reported as NaN online
        'top_5_acc': 0.0, # Reported as NaN online
        'params': 138.4,
        'gflops': 15.4 ,
        'feature_dimension': 4096,
    },
    'VGG19_BN': {
        'model': models.vgg19_bn,
        'weights': models.VGG19_BN_Weights.IMAGENET1K_V1,
        'linear_head_path': ['classifier', 6],
        'feature_dim': 0,
        'top_1_acc': 74.218,
        'top_5_acc': 91.842,
        'params': 143.7,
        'gflops': 19.63,
        'feature_dimension': 4096,
    },
    'VGG19': {
        'model': models.vgg19,
        'weights': models.VGG19_Weights.IMAGENET1K_V1,
        'linear_head_path': ['classifier', 6],
        'feature_dim': 0,
        'top_1_acc': 72.376,
        'top_5_acc': 90.876,
        'params': 143.7,
        'gflops': 19.63,
        'feature_dimension': 4096,
    },
    'ViT_B_16_V1': {
        'model': models.vit_b_16,
        'weights': models.ViT_B_16_Weights.IMAGENET1K_V1,
        'linear_head_path': ['heads', 0],
        'feature_dim': 0,
        'top_1_acc': 81.072,
        'top_5_acc': 95.318,
        'params': 86.6,
        'gflops': 17.56,
        'feature_dimension': 768,
    },
    'ViT_B_16_SWAG_E2E_V1': {
        'model': models.vit_b_16,
        'weights': models.ViT_B_16_Weights.IMAGENET1K_SWAG_E2E_V1,
        'linear_head_path': ['heads', 0],
        'feature_dim': 0,
        'top_1_acc': 85.304,
        'top_5_acc': 97.65,
        'params': 86.9,
        'gflops': 55.48,
        'feature_dimension': 768,
    },
    'ViT_B_16_SWAG_LINEAR_V1': {
        'model': models.vit_b_16,
        'weights': models.ViT_B_16_Weights.IMAGENET1K_SWAG_LINEAR_V1,
        'linear_head_path': ['heads', 0],
        'feature_dim': 0,
        'top_1_acc': 81.886,
        'top_5_acc': 96.18,
        'params': 86.6,
        'gflops': 17.56,
        'feature_dimension': 768,
    },
    'ViT_B_32': {
        'model': models.vit_b_32,
        'weights': models.ViT_B_32_Weights.IMAGENET1K_V1,
        'linear_head_path': ['heads', 0],
        'feature_dim': 0,
        'top_1_acc': 75.912,
        'top_5_acc': 92.466,
        'params': 88.2,
        'gflops': 4.41,
        'feature_dimension': 768,
    },
    'ViT_H_14_SWAG_E2E_V1': {
        'model': models.vit_h_14,
        'weights': models.ViT_H_14_Weights.IMAGENET1K_SWAG_E2E_V1,
        'linear_head_path': ['heads', 0],
        'feature_dim': 0,
        'top_1_acc': 88.552,
        'top_5_acc': 98.694,
        'params': 633.5,
        'gflops': 1016.72,
        'feature_dimension': 1280,
    },
    'ViT_H_14_SWAG_LINEAR_V1': {
        'model': models.vit_h_14,
        'weights': models.ViT_H_14_Weights.IMAGENET1K_SWAG_LINEAR_V1,
        'linear_head_path': ['heads', 0],
        'feature_dim': 0,
        'top_1_acc': 85.708,
        'top_5_acc': 97.73,
        'params': 632.0,
        'gflops': 167.29,
        'feature_dimension': 1280,
    },
    'ViT_L_16_V1': {
        'model': models.vit_l_16,
        'weights': models.ViT_L_16_Weights.IMAGENET1K_V1,
        'linear_head_path': ['heads', 0],
        'feature_dim': 0,
        'top_1_acc': 79.662,
        'top_5_acc': 94.638,
        'params': 304.3,
        'gflops': 61.55,
        'feature_dimension': 1024,
    },
    'ViT_L_16_SWAG_E2E_V1': {
        'model': models.vit_l_16,
        'weights': models.ViT_L_16_Weights.IMAGENET1K_SWAG_E2E_V1,
        'linear_head_path': ['heads', 0],
        'feature_dim': 0,
        'top_1_acc': 88.064,
        'top_5_acc': 98.512,
        'params': 305.2,
        'gflops': 361.99,
        'feature_dimension': 1024,
    },
    'ViT_L_16_SWAG_LINEAR_V1': {
        'model': models.vit_l_16,
        'weights': models.ViT_L_16_Weights.IMAGENET1K_SWAG_LINEAR_V1,
        'linear_head_path': ['heads', 0],
        'feature_dim': 0,
        'top_1_acc': 85.146,
        'top_5_acc': 97.422,
        'params': 304.3,
        'gflops': 61.55,
        'feature_dimension': 1024,
    },
    'ViT_L_32': {
        'model': models.vit_l_32,
        'weights': models.ViT_L_32_Weights.IMAGENET1K_V1,
        'linear_head_path': ['heads', 0],
        'feature_dim': 0,
        'top_1_acc': 76.972,
        'top_5_acc': 93.07,
        'params': 306.5,
        'gflops': 15.38,
        'feature_dimension': 1024,
    },
    'Wide_ResNet101_2_V1': {
        'model': models.wide_resnet101_2,
        'weights': models.Wide_ResNet101_2_Weights.IMAGENET1K_V1,
        'linear_head_path': ['fc'],
        'feature_dim': 0,
        'top_1_acc': 78.848,
        'top_5_acc': 94.284,
        'params': 126.9,
        'gflops': 22.75,
        'feature_dimension': 2048,
    },
    'Wide_ResNet101_2_V2': {
        'model': models.wide_resnet101_2,
        'weights': models.Wide_ResNet101_2_Weights.IMAGENET1K_V2,
        'linear_head_path': ['fc'],
        'feature_dim': 0,
        'top_1_acc': 82.51,
        'top_5_acc': 96.02,
        'params': 126.9,
        'gflops': 22.75,
        'feature_dimension': 2048,
    },
    'Wide_ResNet50_2_V1': {
        'model': models.wide_resnet50_2,
        'weights': models.Wide_ResNet50_2_Weights.IMAGENET1K_V1,
        'linear_head_path': ['fc'],
        'feature_dim': 0,
        'top_1_acc': 78.468,
        'top_5_acc': 94.086,
        'params': 68.9,
        'gflops': 11.4,
        'feature_dimension': 2048,
    },
    'Wide_ResNet50_2_V2': {
        'model': models.wide_resnet50_2,
        'weights': models.Wide_ResNet50_2_Weights.IMAGENET1K_V2,
        'linear_head_path': ['fc'],
        'feature_dim': 0,
        'top_1_acc': 81.602,
        'top_5_acc': 95.758,
        'params': 68.9,
        'gflops': 11.4,
        'feature_dimension': 2048,
    },
}
